---
title: "Models"
author: "Francesca Giacco"
date: "2023-03-26"
output: html_document
---
```{r}
#load packages 
library(tidyverse)
library(ggplot2)
```


```{r}
#load data  (texts)
data<- read_csv("dws_clean.csv")
head(data)

data2<- read_csv("dws2_clean.csv")

```


```{r}

#check if there is some kind of correlation between victim blaming in title and in text 
ggplot(data, aes(x=tit_vb, y=text_vb)) + geom_point() + geom_smooth(method = "lm")


#further cleaning 
data<- data %>% 
  #mutate(vict_blamer=round(vict_blame, 2)) %>% 
  #only differenciate btw italian/non italian
  mutate(killer_origin=(ifelse(Paese.di.origine.presunt..colpevole=="Italia", 1, 0))) %>% 
  mutate(victim_origin=(ifelse(Paese.di.origine.persona.uccisa=="Italia", 1, 0))) %>% 
  #make age categorical
  mutate(age=ifelse(Età.persona.uccisa<5, "baby", 
             ifelse(Età.persona.uccisa<15, "kid", 
             ifelse(Età.persona.uccisa<25, "adolescent", 
             ifelse(Età.persona.uccisa<40,"early_adult", 
             ifelse(Età.persona.uccisa<60,"adult", 
             ifelse(Età.persona.uccisa<70 ,"early_old", "old" ))))))) %>% 
  mutate(gender.j=ifelse(gender.j==0, 0,
                  ifelse(gender.j==1, 1, 
                  ifelse(gender.j==2, 2,
                  ifelse(gender.j==3, 1,
                  ifelse(gender.j==4, 0,2 )))))) %>% 
  #attention: everytime it multiplies by 100
  mutate(text_vb=text_vb*100) %>% 
  mutate(tit_vb=tit_vb*100)
  



ggplot(data, aes(x=tit_vb)) + geom_histogram()
```

```{r}
#write models 
colnames(data)

table(data$Sex.worker)


lm1 = lm(tit_vb~  killer_origin  + victim_origin + Relazione.con.la.persona.uccisa..semplificata. + gender.j + local +  Suicidio.presunt..colpevole + age , data = data) #Create the linear regression
summary(lm1) #Review the results

lm2 = lm(text_vb~  killer_origin  + victim_origin + Relazione.con.la.persona.uccisa..semplificata. + gender.j + local +  Suicidio.presunt..colpevole + age + victim_origin*killer_origin + tit_vb , data = data) #Create the linear regression
summary(lm2)


```
```{r}

data1<- data %>% 
          group_by(victim) %>% 
                summarise(mean(tit_vb))
data1

max_tvb<- data %>% slice_max(text_vb)
max_tvb$text
  
table(data$vict_blamer)

data2<- data %>% 
          group_by(newspaper) %>% 
                summarise(mean(text_vb))
data2
```

